name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-13]
    runs-on: ${{ matrix.platform }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run lint
        if: matrix.platform == 'ubuntu-latest'
        uses: reviewdog/action-golangci-lint@v2

      - name: Run tests
        run: make ci

      - name: Run octocov
        if: matrix.platform == 'ubuntu-latest'
        uses: k1LoW/octocov-action@v0
